config/routes.rb
Rails.application.routes.draw do
  

  
  resources :share_albums
  

  get 'home/index'
  
  devise_for :users

  resources :users do
    resources :albums do
      resources :photos do
	      member do
		get 'set_cover'
	      end
	resources :comments
	end
    end
  end
  

  root 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :photos
  has_many :share_albums
  has_many :comments , through: :photos
  belongs_to :user
   validates :title, uniqueness:true
   validates :title, :describtion, presence:true,length: { minimum: 5}
    
  before_validation :check 

    def check
      title = describtion if title.blank?
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end
  
  def index
    @albums = current_user.albums
  end

  def show
     @album = Album.find(params[:id])
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    respond_to do |format|
      format.html { redirect_to user_albums_path(current_user, @photo.album), notice: 'album was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
    
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    
   respond_to do |format|
      if @album.update_attributes(album_params)
        format.html { redirect_to  user_albums_path }
	format.js {}
      else
	format.js
	format.html { render 'edit'}
      end
    end
  end 

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id
    
    respond_to do |format|
      if @album.save
	  format.html { redirect_to  user_albums_path }
	  format.js
      else
        format.html { render :new }
      end
    end
  end

  private
    def album_params
      params.require(:album).permit(:title, :describtion)
    end
end

app/helpers/album_helper.rb
module AlbumHelper
  def get_photo_url(album)
    url = "cover.jpeg"
    if album.cover_id.present?
      photo = Photo.find(album.cover_id)
      url = photo.avatar.url
    end
    return url
  end
end

app/views/albums/_album.html.erb
<div id="album_<%= album.id %>" >
   <div><b><%= album.title %></div></b>
      <div><%= link_to image_tag(get_photo_url(album)) , user_album_path(current_user, album) %>  
	<%= link_to 'Edit',  edit_user_album_path(current_user, album) %>
	<%= link_to 'Destroy', user_album_path(current_user, album) , method: :delete,:remote => true,:class => 'delete_photo', data: { confirm: 'Are you sure?' } %>
	<%= link_to 'shared', new_share_album_path(album)%>
      </div>
   </br>
</div>

app/views/albums/_comment.html.erb
  
  <div id="comment_<%= comment.id %>">
      <div>
        <b><%= comment.user.user_name %></b> :: 
        <%= comment.user_comment %>&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_user_album_photo_comment_path(current_user ,@album, comment.photo.id, comment) %> 
        <%= link_to 'Delete', user_album_photo_comment_path(current_user ,@album, comment.photo.id, comment ), method: :delete,:remote => true, data: { confirm: 'Are you sure?' } %></br>
      </div>
  </div>

app/views/albums/_form.html.erb
<%= form_for [current_user, @album] do |f| %>
<% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :describtion %><br>
    <%= f.text_area :describtion %>
  </p>
 
  <p>
     <%= f.submit value ="create" ,{:class=>"savebutton"} %>
  </p>
<% end %>

app/views/albums/_photo.html.erb
  
  <style> 
    .show1
      {
	padding-top: 25px;
	display:none;
      }
  </style>
    <div id="photo_<%= photo.id %>" >
        <div id="update_photo">
	      <%= link_to 'Edit', edit_user_album_photo_path(current_user, @album, photo) %>
	       <%= link_to 'Destroy', user_album_photo_path(current_user , @album, photo), method: :delete, :remote => true,:class => 'delete_photo', data: { confirm: 'Are you sure?' } %>
              <span class="new1" id="<%= photo.id %>">comment</span>
	       <%= link_to 'Add coverpage', set_cover_user_album_photo_path(current_user ,@album, photo.id ) %>
        </div>
    
	       <div>
	           <%= image_tag photo.avatar.url %>
	       </div>
  
	     
	             <div id="comment">
	                 <% photo.comments.each do |comment| %>
	                 <%= render :partial => 'comment', :locals => { :comment => comment, :photo => photo,:album => photo.album_id} %>
	                 <% end %>
	             </div>
	  
	                 <div class ="show1" >
                            <%= render :partial => "comments/form", :locals => {:user => current_user, :album => @album, :@photo => photo, :@comment => photo.comments.new} %>
                        </div>
                        <br>
    </div>


 <script type="text/javascript">
    $(document).ready(function(){
          $(".new1").click(function(){
            $("#show").hide();
      });
    });
  </script>

app/views/albums/destroy.js.erb
$("#album_<%=@album.id%>").remove();

app/views/albums/edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@album.title}" %></h3>
</div>

<%= render 'form' %>

app/views/albums/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/albums/index.html.erb
<div id ="index">
  <h3>All Alblums</h3>
    <div id ="album">
      <% @albums.each do |album| %>
	<%= render :partial => 'album', :locals => { :album => album} %>
      <% end %>
    </div>
</div>

app/views/albums/new.html.erb
<div class="modal-header">
<h3>New Album</h3>
</div>

<%= render 'form' %>

app/views/albums/show.html.erb
<style> 
  #show
    {
      padding-top: 25px;
      display:none;
    }

</style>
    <div id="new" ><h3>new photo<h3></div>
      <div id ="photo">
	<% @album.photos.each do |photo| %>
	<%= render :partial => 'photo', :locals => { :photo => photo} %>

	<% end %>

    <div id="show" >
      <%= render :partial => "photos/form", :locals => {:user => current_user, :album => @album, :@photo => @album.photos.new} %>
    </div>
    
  </div>

  <script type="text/javascript">
     $(document).ready(function(){
      $("#new").click(function(){
          $("#show").slideToggle("slow");
        });
        $("#new").click(function(){
          $(".show1").hide();
           });
          $(".new1").click(function(){
            $('.show1').each(function() {
                if ($(this).css('display') == 'block') {
                    $(this).slideToggle("slow");
                }
            });
            var photo_id = this.id;
            setTimeout(function(){$("#photo_" + photo_id + " .show1").slideToggle("slow")}, 100);
          });
    });
  </script>
 

app/views/albums/update.js.erb
<% if @album.errors.count > 0 %>
  alert('error')
<% else %>
alert ()
<% end %>