config/routes.rb
Rails.application.routes.draw do
  

  
  resources :share_albums
  

  get 'home/index'
  
  devise_for :users

  resources :users do
    resources :albums do
      resources :photos do
	      member do
		get 'set_cover'
	      end
	resources :comments
	end
    end
  end
  

  root 'home#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :avatar
   
  validates_attachment_presence :avatar

  has_many :comments
  belongs_to :album
  validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	# GET /photos
	# GET /photos.json
	respond_to :js, :html
	def index
		@user = current_user
		@album = Album.find(params[:album_id])
		@photos = Photo.all
	end

	# GET /photos/1
	# GET /photos/1.json
	def show
	 @photo = Photo.find(params[:id]) 
	end

	# GET /photos/new
	def new
		@album = Album.find(params[:album_id])
		@photo = Photo.new
	end

	# GET /photos/1/edit
	def edit
		@album = Album.find(params[:album_id])
		@photo = Photo.find(params[:id])
	end
	
	def set_cover
		@album = Album.find(params[:album_id])
		if @album.update_attributes(:cover_id => params[:id])
			flash[:notice] = 'Photo has been set as a cover photo'
			redirect_to user_albums_path
		else
			
		end
	end

	# POST /photos
	# POST /photos.json
	
	def create
		@photo = Photo.new(photo_params)
		@album = Album.find(params[:album_id])
		respond_to do |format|
			if @photo.save
				format.html { redirect_to  user_album_path(current_user, @photo.album), notice: 'Photo was successfully created.' }
				format.js   { }
			else
				format.html { render :new, :user_id => current_user.id, :album_id => @album.id }
			end
		end
	end

	# PATCH/PUT /photos/1
	# PATCH/PUT /photos/1.json
	def update
		@photo = Photo.find(params[:id])
		@album = Album.find(params[:album_id])
		respond_to do |format|
			if @photo.update(photo_params)
				format.html { redirect_to  user_album_path(current_user, @photo.album) }
				#format.json { render :show, status: :ok, location: @photo }
				format.js { }
			else
				format.html { render :edit }
				format.json { render json: @photo.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /photos/1
	# DELETE /photos/1.json
	
	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy
		album= @photo.album 
		if album.cover_id == @photo.id
			album.update_attributes(:cover_id => nil)
		end
		
		respond_to do |format|
			format.html { redirect_to user_album_path(current_user, @photo.album), notice: 'Photo was successfully destroyed.' }
			format.json { head :no_content }
			format.js   { render :layout => false }
		end
	end




	private
	# Never trust parameters from the scary internet, only allow the white list through.
	def photo_params
		params.require(:photo).permit(:album_id, :avatar)
	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for [current_user, @album, @photo ],:remote => true,:authenticity_token => true do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :album_id, :value => @album.id %>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit value ="create" ,{:class=>"savebutton"} %>
  </div>
<% end %>

app/views/photos/create.js.erb
$("#photo").prepend("<%= escape_javascript render :partial => 'albums/photo', :locals => { :photo => @photo}  %>");
$("#show").slideToggle("slow");

app/views/photos/destroy.js.erb
$("#photo_<%=@photo.id%>").remove();

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', user_album_photo_path(current_user, @photo.album, @photo) %> |
<%= link_to 'Back', user_album_photos_path(current_user, @photo.album) %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.avatar.url %></td>
        <td><%= link_to 'Show', user_album_photo_path(current_user, photo.album_id, photo) %></td>
        <td><%= link_to 'Edit', edit_user_album_photo_path(current_user, photo.album_id, photo) %> </td>
        <td><%= link_to 'Destroy', user_album_photo_path(current_user , photo.album_id, photo), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_user_album_photo_path(current_user, @album.id) %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @photo.album_id %>
</p>

<p>
  <strong>Avatar:</b>
  <%= image_tag @photo.avatar.url %>
</p>

app/views/photos/update.js.erb
$("#update_photo").prepend("<%= escape_javascript render :partial => 'albums/photo', :locals => { :photo => @photo}  %>");