config/routes.rb
Rails.application.routes.draw do
  

  
  resources :share_albums
  

  get 'home/index'
  
  devise_for :users

  resources :users do
    resources :albums do
      resources :photos do
	      member do
		get 'set_cover'
	      end
	resources :comments
	end
    end
  end
  

  root 'home#index'

end

app/views/layouts/aapplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gellary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
  <% if current_user.present? %>
    <%= link_to 'Logout', destroy_user_session_path, :method => 'delete' %>
    &nbsp;&nbsp;&nbsp;
    <%= link_to 'view albums', user_albums_path(current_user) %>

    &nbsp;&nbsp;&nbsp;
    <%= link_to 'create new', new_user_album_path(current_user) %>
  <% else %>
    <%= link_to 'SignIn', new_user_session_path %>
    <%= link_to 'Singup', new_user_registration_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gellary" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Gellary</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
	      <% if current_user.present? %>
		<li><%= link_to 'Logout', destroy_user_session_path, :method => 'delete' %></li>
		<li><%= link_to 'Albums', user_albums_path(current_user) %></li>
	      <% else %>
		<li><%= link_to 'SignIn', new_user_session_path %></li>
		<li><%= link_to 'Singup', new_user_registration_path %></li>
	      <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
	<% if current_user.present? %>
	  <div class="span3">
	      <div class="well sidebar-nav">
		<ul class="nav nav-list">
		  <li class="nav-header">More Options</li>
		  <li><%= link_to "My Albums",user_albums_path(current_user) %></li>
		  <li><%= link_to 'New album', new_user_album_path(current_user) %></li>
		  <li><%= link_to 'shared album', new_share_album_path %></li>
		
		</ul>
	      </div><!--/.well -->
	  </div><!--/span-->
	<% end %>
	<% cname = current_user.present? ? "span9" : "span12" %>
        <div class="<%= cname %>">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>